config/routes.rb
Dinesh::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

match 'logout' => 'sessions#destroy', :as => :logout

  match 'employee'=>'users#employee'

  match 'message/:id'=>'users#message'

match 'inbox'=>'users#inbox'

match 'create'=>'users#create'

match '/dashboard'=>'users#dashboard'

match '/users/dashboard/message=:id'=>'users#dashboard'

match 'create1'=>'users#create1'

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

	root :to =>"sessions#new"

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
	
	has_many :messages
	
	
	include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken

  set_table_name 'users'

  validates :login, :presence   => true,
                    :uniqueness => true,
                    :length     => { :within => 3..40 },
                    :format     => { :with => Authentication.login_regex, :message => Authentication.bad_login_message }

  validates :name,  :format     => { :with => Authentication.name_regex, :message => Authentication.bad_name_message },
                    :length     => { :maximum => 100 },
                    :allow_nil  => true,
                     :presence   => true

  validates :email, :presence   => true,
                    :uniqueness => true,
                    :format     => { :with => Authentication.email_regex, :message => Authentication.bad_email_message },
                    :length     => { :within => 6..100 }

  validates :lastname, :presence   => true
  	
  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :name, :password, :password_confirmation, :lastname



  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_by_login(login.downcase) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  protected
    


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Be sure to include AuthenticationSystem in Application Controller instead
	require'authenticated_system.rb'
	include AuthenticatedSystem
	before_filter :force_login, :except=>[:create,:new]
      
	layout "application",:except=>[:message]
	

	PAGINATION_COUNT = Message::PER_PAGE
  PER_PAGE = 5

  # render new.rhtml
  def new
    @user = User.new
  end
 
  def create
    logout_keeping_session!
    @user = User.new(params[:user])
    success = @user && @user.save
    if success && @user.errors.empty?
            # Protects against session fixation attacks, causes request forgery
      # protection if visitor resubmits an earlier form using back
      # button. Uncomment if you understand the tradeoffs.
      # reset session
      self.current_user = @user # !! now logged in
      redirect_to('/login', :notice => "Thanks for signing up!")
    else
      flash.now[:error]  = "We couldn't set up that account, sorry.  Please try again, or contact an admin (link is above)."
			
      render :action=>'new'
    end
end

def create1
	@message=Message.new(:message=>params[:message], :user_id=>params[:user_id], :is_display=>'0')
	@message.save
	redirect_to("/employee" , :notice => "Message has been successfully sent")
end

def employee
	@employee=User.all
end

def message
	@employee=User.find_by_id(params[:id])
end

def inbox
	@messages=current_user.messages
  #~ @details_inbox = @messages.paginate(:page=>params[:page],:per_page=>PAGINATION_COUNT )      
	#~ @messages = @details_inbox
  
end

def dashboard
	if params[:id] 
	@mess=Message.find_by_id(params[:id])
		if @mess.is_display==false   
		@mess.update_attribute('is_display',1)
		else
		@mess.update_attribute('is_display',0)
		end
	end
	 @messages_dashboard=Message.find(:all,:conditions=>['is_display=?',1], :order => "updated_at DESC")
	 @details = @messages_dashboard.paginate(:page=>params[:page],:per_page=>PAGINATION_COUNT )      
	 @messages_dashboard  = @details

end
end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_leftpanel.html.erb
<div id="navigation">
<p>
<a href="/employee">Employee List</a>
</p>
<p>
<a href="/inbox">Inbox</a>
</p>
<p>
<a href="/dashboard">Dashboard</a>
</p>
</div>

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/dashboard.html.erb
<div class="posts">
<div class="container">
	<div class="width-wrapper">
		<div id="posts" class="left-col main-content">
			<ul class="nav-tabs">
				<li class="active"><a href=<%=dashboard_url%>>Dashboard</a><div class="tab-right"></div></li>               
				<li ><h1><a href=<%=inbox_url%>>Inbox</a></h1><div class="tab-right"></div></li>
				<li ><h1><a href=<%=employee_url%>>Employees</a></h1><div class="tab-right"></div></li>
			</ul>
			<div class="box-top-left"></div>
			<div class="box-top"><font color="green"><p align="center"><%=flash[:notice]%></p></font></div>
			<div class="box-top-right"></div>
			<div class="main-padder">
				<div class="dash-box">

					<h2 class="header-bar">Posts</h2>
					<div class="header-tools">
						
					</div>
				</div>
				<%@messages_dashboard.each do |dash|%>
				<div id="post-1">
					<div class="avatar-header topless">
						<img alt="user1" src="images/users/user1.jpg" />
						<h3><a href="/post-view">Nike Rebranding Proposal with Coca-Cola</a></h3>
						<p class="desc"><strong>Last comment by Stuart B.</strong> on Thursday, August 26</p>
					</div>
					<div class="post-body">
						<p><%=dash.message%></p>
					</div>

					<div class="post-footer">
                    	<p ><strong>Publish:<%=User.find_by_id(dash.user_id).name%></strong></p>
						<div class="box-bottom-left"></div>
						<div class="box-bottom-right"></div>
					</div>
				</div>
				<%end%>
				<%=will_paginate @messages_dashboard%>
<!--[if IE 6]>
<script type="text/javascript">
    /*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; }
    var IE6UPDATE_OPTIONS = {
        icons_path: "http://static.ie6update.com/hosted/ie6update/images/"
    }
</script>
<script type="text/javascript" src="http://static.ie6update.com/hosted/ie6update/ie6update.js"></script>
<![endif]-->
</div>

app/views/users/employee.html.erb
<div class="posts">
<%= javascript_include_tag "prototype.js" %>
<%= javascript_include_tag "control_modal.js" %>


 <%= stylesheet_link_tag "control_modal"%>

 <%= javascript_include_tag "effects.js"%>
<%= javascript_include_tag "dragdrop.js"%>
<%= javascript_include_tag "scriptaculous.js"%>
<%= javascript_include_tag "builder.js"%> 
<%= javascript_include_tag "controls.js"%>
<%= javascript_include_tag "application.js" %>
<div class="container">
	<div class="width-wrapper">
		<div id="people-permissions" class="left-col main-content">
			<ul class="nav-tabs">
				<li><a href=<%=dashboard_url%>>Dashboard</a><div class="tab-right"></div></li>				
				<li><a href=<%=inbox_url%>>Inbox</a><div class="tab-right"></div></li>
				<li class="active"><a href=<%=employee_url%>>Employees</a><div class="tab-right"></div></li>
			</ul>
			<div class="box-top-left"></div>
			<div class="box-top"></div>
			<div class="box-top-right"></div>
			<div class="main-padder">
				<div class="dash-box">
					<h2 class="header-bar">People &amp; Permissions</h2>
					<div class="padder dark-bg">
						<ul class="contact-list">
						<%@employee.each do |employee|%>
						<%if employee.id!=current_user.id%>
							<li class="card">							
								<div class="header avatar-header">
									<img class="avatar" alt="Avatar" src="images/users/user1.jpg" />
									<h4><%= link_to employee.login, "/message/#{employee.id}" ,:id=>"list_#{employee.id}",:remote=>'true'%></h4>
									
									<p class="desc">Director</p>
									<a class="f-rgt btn ir edit-icon" href="/profile-edit" title="Edit"><span>Mail</span></a>				
								</div>
							</li>
							<%end%> 
								<%end%>   
						</ul>
					</div>
				</div>
			</div> <!-- end main-padder -->
			<div class="box-bottom-left"></div>
			<div class="box-bottom"></div>
			<div class="box-bottom-right"></div>
		</div>
	</div>

	
</div>
<div id="footer" class="width-wrapper">
	<p class="left-col"></p>

</div>
<!--[if IE 6]>
<script type="text/javascript">
    /*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; }
    var IE6UPDATE_OPTIONS = {
        icons_path: "http://static.ie6update.com/hosted/ie6update/images/"
    }
</script>
<script type="text/javascript" src="http://static.ie6update.com/hosted/ie6update/ie6update.js"></script>
<![endif]-->
</div>

app/views/users/inbox.html.erb
<div class="posts">
<%= javascript_include_tag :defaults %>
<div class="container">
	<div class="width-wrapper">
		<div id="posts" class="left-col main-content">
			<ul class="nav-tabs">
				<li><a href=<%=dashboard_url%>>Dashboard</a><div class="tab-right"></div></li>              
				<li class="active"><h1><a href=<%=inbox_url%>>Inbox</a></h1><div class="tab-right"></div></li>
				<li><h1><a href=<%=employee_url%>>Employees</a></h1><div class="tab-right"></div></li>
			</ul>
			<div class="box-top-left"></div>
			<div class="box-top"></div>
			<div class="box-top-right"></div>
			<div class="main-padder">
				<div class="dash-box">

					<h2 class="header-bar">Posts</h2>
					<div class="header-tools">
						
					</div>
				</div>
				
<%@messages.each do |m|%>
<%if m.is_display==true%>
				<div id="post-1">
					<div class="avatar-header topless">
						<img alt="user1" src="images/users/user1.jpg" />

						<h3><a href="/post-view">Nike Rebranding Proposal with Coca-Cola</a></h3>
						<p class="desc"><strong>Last comment by Stuart B.</strong> on Thursday, August 26</p>
					</div>
					<div class="post-body">
						<p><%=m.message%></p>
					</div>

					<div class="post-footer">
           <p >         	
				<input type="checkbox" name="message" value="1" id="<%=m.id%>" onclick="modify_db('<%=m.id%>');" checked /> <%='Publish'%>
					</p>
						<div class="box-bottom-left"></div>
						<div class="box-bottom-right"></div>
					</div>
				</div>
	<%else%>
	<div id="post-1">
					<div class="avatar-header topless">
						<img alt="user1" src="images/users/user1.jpg" />

						<h3><a href="/post-view">Nike Rebranding Proposal with Coca-Cola</a></h3>
						<p class="desc"><strong>Last comment by Stuart B.</strong> on Thursday, August 26</p>
					</div>
					<div class="post-body">
						<p><%=m.message%></p>
					</div>

					<div class="post-footer">
                    	<p >
<input type="checkbox" name="message" value="1" id="<%=m.id%>" onclick="modify_db('<%=m.id%>');" /> <%='Publish'%>
</p>
						<div class="box-bottom-left"></div>
						<div class="box-bottom-right"></div>
					</div>
				</div>
				<%end%>
				<%end%>
<!--[if IE 6]>
<script type="text/javascript">
    /*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; }
    var IE6UPDATE_OPTIONS = {
        icons_path: "http://static.ie6update.com/hosted/ie6update/images/"
    }
</script>
<script type="text/javascript" src="http://static.ie6update.com/hosted/ie6update/ie6update.js"></script>
<![endif]-->
</div>

app/views/users/message.html.erb
	 <%= stylesheet_link_tag "control_modal"%>
 <%= stylesheet_link_tag "default"%>
<div style="background-color:#FFFFFF; border:1px solid #CDD3D8; float:left; width:404px;height:300px;">

<div class="light_box_close"><a onclick="document.getElementById('modal_container').style.display='none';document.getElementById('modal_overlay').style.display='none'" href="javascript:void(0)"><img alt="close" src="/images/delete.png"></a></div>
<div class="lightbox_header">Message to: <%= @employee.login%></div>
<% form_tag(create1_path, :method=>'post', :multipart => true) do %>
   <%=text_area_tag "message", "", :size=>"45x6"  %>
   <input name="user_id" type="hidden" value=<%=@employee.id%> />
   <%= submit_tag 'Submit' %>
<% end %>
</div>

app/views/users/new.html.erb
<div class="dialog signup">
<div class="content-wrap">
			<div class="box-wrap">
				<div class="box">
					<h1>Start your 30-Day Free Trial</h1>
					<p><em>Everything is fully functional. No credit card is required</em></p>
<% @user.password = @user.password_confirmation = nil %>
					<%= form_for :user, :url => users_path do |f| -%>
						<fieldset class="share-line">
						<label>Login</label>
								<div class="input-wrapper text-wrapper ">
		<div class="box-top-left"></div>
		<div class="box-top"></div>
		<div class="box-top-right"></div>
		<div class="box-body">

			<%= f.text_field :login %>
		</div>
		<div class="box-bottom-left"></div>
		<div class="box-bottom"><font color='red'><%=error_message_on :user, :login%></font></div>
		<div class="box-bottom-right"></div>
	</div>
							<label>First Name</label>
								<div class="input-wrapper text-wrapper ">
		<div class="box-top-left"></div>
		<div class="box-top"></div>
		<div class="box-top-right"></div>
		<div class="box-body">

			<%= f.text_field :name %>
		</div>
		<div class="box-bottom-left"></div>
		<div class="box-bottom"><font color='red'><%=error_message_on :user, :name%></font></div>
		<div class="box-bottom-right"></div>
	</div>

								<label>Last Name</label>
								<div class="input-wrapper text-wrapper ">

		<div class="box-top-left"></div>
		<div class="box-top"></div>
		<div class="box-top-right"></div>
		<div class="box-body">
			<%= f.text_field :lastname %>
		</div>
		<div class="box-bottom-left"></div>
		<div class="box-bottom"><font color='red'><%=error_message_on :user, :lastname%></font></div>
		<div class="box-bottom-right"></div>

	</div>

								<label>Email</label>
								<div class="input-wrapper text-wrapper ">
		<div class="box-top-left"></div>
		<div class="box-top"></div>
		<div class="box-top-right"></div>
		<div class="box-body">
			<%= f.text_field :email %>

		</div>
		<div class="box-bottom-left"></div>
		<div class="box-bottom"><font color='red'><%=error_message_on :user, :email%></font></div>
		<div class="box-bottom-right"></div>
	</div>

								<label>Password</label>
								<div class="input-wrapper text-wrapper ">
		<div class="box-top-left"></div>

		<div class="box-top"></div>
		<div class="box-top-right"></div>
		<div class="box-body">
			<%= f.password_field :password %>
		</div>
		<div class="box-bottom-left"></div>
		<div class="box-bottom"><font color='red'><%=error_message_on :user, :password%></font></div>
		<div class="box-bottom-right"></div>
	</div>

								<label>Confirmation Password</label>
								<div class="input-wrapper text-wrapper ">
		<div class="box-top-left"></div>
		<div class="box-top"></div>
		<div class="box-top-right"></div>
		<div class="box-body">
			<%= f.password_field :password_confirmation %>
		</div>

		<div class="box-bottom-left"></div>
		<div class="box-bottom"><font color='red'><%=error_message_on :user, :password_confirmation%></font></div>
		<div class="box-bottom-right"></div>
	</div>

								
								

							<p class="fine-print">By clicking <em>'Create my account,'</em> you agree to the <a href="/terms">Terms of Use</a> and <a href="/privacy">Privacy Policy</a>.</p>
							
							<%= submit_tag 'Sign up',:class=>'btn-47 create-account-btn' %>
						</fieldset>
					<%end%>
				</div>
			</div>
		</div>
		</div>