config/routes.rb
Dinesh::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

match 'logout' => 'sessions#destroy', :as => :logout

  match 'employee'=>'users#employee'

  match 'message/:id'=>'users#message'

match 'inbox'=>'users#inbox'

match 'create'=>'users#create'

match '/dashboard'=>'users#dashboard'

match '/users/dashboard/message=:id'=>'users#dashboard'

match 'create1'=>'users#create1'

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

	root :to =>"sessions#new"

end

app/views/layouts/_afternavigation.html.erb
<div id="navigation">
<p>
<a href="/employee">Employee List</a>
</p>
<p>
<a href="/inbox">Inbox</a>
</p>
<p>
<a href="/dashboard">Dashboard</a>
</p>
<p>
<a href="/logout">Logout</a>
</p>
</div>

app/views/layouts/_beforenavigation.html.erb
<div id="navigation">
<p>
<a href="/signup">Signup</a>
</p>
<p>
<a href="/login">Login</a>
</p>
<p>
</p>
</div>

app/views/layouts/_footer.html.erb
<div id="footer"><p></p></div>

app/views/layouts/_header.html.erb
<div id="container">
<div id="header"><h1><image src="/images/rf.jpg"></h1></div>
<div id="wrapper">
<div id="content">

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head profile="http://gmpg.org/xfn/11">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Sign Up | CoThink.it</title>

			<meta name="robots" content="INDEX,FOLLOW" />
	


 <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
	
<!--[if lt IE 7]>
<script src="http://ie7-js.googlecode.com/svn/version/2.0(beta3)/IE7.js" type="text/javascript"></script>
<![endif]-->
		<script type="text/javascript" src="http://use.typekit.com/kho4jtx.js"></script>

	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
	<link rel="shortcut icon" href="images/favicon.ico" />

</head>


<body>

		<div id="bg-top"></div>
		<div id="top">
			
			<h2 id="logo" class="ir"><a href="/"><span></span></a></h2>
			<%if logged_in?%>
			<p id="login-blurb"><%=current_user.name%>|<%=link_to "Logout",logout_url%></p>
			<%else%>
			<p id="login-blurb">Create a new account? <%=link_to "Sign Up",signup_url%></p>
			<p id="login-blurb1">Login into your account? <%=link_to "Login",login_url%></p>

			<%end%>
		</div>
		<%=yield%>		
	</body>
</html>